ssh:
  host: your_remote_host
  port: 22
  username: your_username
  password: your_password
folder_in: /home/user/tst
folder_out: /home/user/out
folder_ext: /home/user/folder1
folder_ext2: /home/user/folder2
count: 5
bs: 1M
type: zip
arc_type: zip
